import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/report.dart';
import '../../domain/repositories/report_repository.dart';
import '../models/report_model.dart';

class ReportRepositoryImpl implements ReportRepository {
  final FirebaseFirestore _firestore;

  ReportRepositoryImpl({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  @override
  Future<void> addReport(Report report) async {
    final reportModel = ReportModel(
      id: report.id, // Usually generated by Firestore, but if we pass it...
      firstName: report.firstName,
      lastName: report.lastName,
      age: report.age,
      gender: report.gender,
      country: report.country,
      city: report.city,
      district: report.district,
      latitude: report.latitude,
      longitude: report.longitude,
      category: report.category,
      description: report.description,
      evidenceUrls: report.evidenceUrls,
      createdAt: report.createdAt,
      socialMedia: report.socialMedia,
    );

    // Check if person exists to update or create new?
    // For now, simpler implementation: just add new document or handle logic elsewhere.
    // The prompt implies we might aggregate reports on one person ("Contador total de reportes sobre esta persona").
    // That suggests we should search first. But "Agregar Reporte" usually adds a new entry.
    // However, the profile shows "Total reports".
    // I'll assume we add a "Report" document, but maybe we link it to a "Person" entity?
    // Or we just query by name. The prompt says "Búsqueda por nombre".
    // Let's store each report as a document. Aggregation can happen on read or via Cloud Functions.

    await _firestore.collection('reports').doc(report.id).set(reportModel.toDocument());
  }

  @override
  Future<List<Report>> getRecentReports({int limit = 50}) async {
    final snapshot = await _firestore
        .collection('reports')
        .orderBy('metadata.createdAt', descending: true)
        .limit(limit)
        .get();

    return snapshot.docs.map((doc) => ReportModel.fromSnapshot(doc)).toList();
  }

  @override
  Future<List<Report>> searchReports(String query, {int? minAge, int? maxAge, String? city}) async {
    // Basic search implementation. Firestore capabilities are limited for partial text search without external services like Algolia.
    // We will use the 'searchKeywords' array approach or simply query by prefix if possible.

    Query q = _firestore.collection('reports');

    if (city != null && city.isNotEmpty) {
      q = q.where('location.city', isEqualTo: city);
    }

    // Note: This is a simplified search. Real-world needs Algolia/ElasticSearch.
    if (query.isNotEmpty) {
       q = q.where('searchKeywords', arrayContains: query.toLowerCase());
    }

    final snapshot = await q.get();
    var results = snapshot.docs.map((doc) => ReportModel.fromSnapshot(doc)).toList();

    // Client side filtering for age/logic if Firestore limitations hit
    if (minAge != null) {
      results = results.where((r) => r.age >= minAge).toList();
    }
    if (maxAge != null) {
      results = results.where((r) => r.age <= maxAge).toList();
    }

    return results;
  }

  @override
  Future<Report?> getReportById(String id) async {
    final doc = await _firestore.collection('reports').doc(id).get();
    if (doc.exists) {
      return ReportModel.fromSnapshot(doc);
    }
    return null;
  }

  @override
  Future<void> voteReport(String reportId, bool isReal) async {
    final field = isReal ? 'votes.real' : 'votes.fake';
    await _firestore.collection('reports').doc(reportId).update({
      field: FieldValue.increment(1),
    });
  }
}
